# Default values for crm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  name: "us-docker.pkg.dev/task-1-375619/dvireview/dvireview"
  tag: 1.4.4

autoscaling: 
  enabled: true
  min: 3
  max: 50
  averageUtilization: 80

#db settings
mongodb:
  replicaCount: 3
  useStatefulSet: true
  arbiter.enabled: false
  metrics.enabled: true
  architecture: replicaset
  auth:
    rootUser: root
    usernames: ["dvir"]
    databases: ["dvireview"]
    existingSecret: mongo-sec
  
nginx:
  replicaCount: 2
    
ingress:
  enabled: true
  host: dvireview.ddns.net
  tls: 
    enabled: true 
    email: "pashutdvir@gmail.com"

kibana:
  serviceName: "elasticsearch-kibana"
  port: "5601"

resources: {
  limits: { cpu: 150m, memory: 128Mi },
  requests: { cpu: 75m, memory: 64Mi } 
  }