
apiVersion: "v1"
kind: "Service"
metadata:
  name: "dvireview-service"
  labels:
    app: "app"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  selector:
    app: "app"
{{- if .Values.ingress.enabled }}
  type: ClusterIP
{{- else }}
  type: "LoadBalancer"
{{- end }}
  
