apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{.Chart.Name}}-deplyment
  #namespace: "project"
  labels:
    app: "app"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "app"
  template:
    metadata:
      labels:
        app: "app"
    spec:
      containers:
      - name: app
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        resources:
{{toYaml .Values.resources | indent 12}}
        env:
        - name: REALEAS
          valueFrom:
            configMapKeyRef: 
              name: mongo-stuff
              key: releas_name
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef: 
              name: mysecret
              key: db-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: mysecret
              key: db-password



---
{{- if .Values.autoscaling.enabled }}
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: {{.Chart.Name}}-autoscaling
  labels:
    app: "app"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: {{.Chart.Name}}-deplyment
    apiVersion: "apps/v1"
  minReplicas: {{.Values.autoscaling.min }}
  maxReplicas: {{.Values.autoscaling.max }}
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: {{.Values.autoscaling.averageUtilization }}
{{- end }}