{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{.Chart.Name}}-cron"
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongodb-drop-db
            image: mongo:6.0.3
            env: 
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef: 
                  name: mongo-stuff
                  key: mongo-url
            command:
            - bash
            - "-c"
            - |
              mongosh "${MONGODB_URI}" --eval "db.dropDatabase()"
          restartPolicy: OnFailure
{{- end }}