apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{.Chart.Name}}-nginx-deplyment
  labels:
    app: "nginx"
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      app: "nginx"
  template:
    metadata:
      labels:
        app: "nginx"
    spec:
      containers:
      - name: nginx
        image: us-docker.pkg.dev/task-1-375619/port-nginx/port-nginx:{{ .Values.image.tag }}