apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-stuff
data:
  presistance: "true"
  log_level: "info"
  mongo-url: {{ printf "mongodb://%s:%s@%s-mongodb-headless" .Values.mongodb.credentials.rootUser .Values.mongodb.credentials.rootPassword $.Release.Name }}