apiVersion: v1
items:
- apiVersion: v1
  data:
    .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlpIWnBjak16T2sxdmRHUmxjR0Z6Y3pFeU13PT0iCgkJfQoJfSwKCSJjcmVkSGVscGVycyI6IHsKCQkidXMtY2VudHJhbDEtZG9ja2VyLnBrZy5kZXYiOiAiZ2Nsb3VkIgoJfQp9
  kind: Secret
  metadata:
    name: regcred
    namespace: default
  type: kubernetes.io/dockerconfigjson
kind: List
metadata:
  resourceVersion: ""
